### ISSUE TITLE
Errors in output when pipe character present in class text.

### ISSUE THREAD

**Issue by wolandscat** [openEHR/spec-publish-asciidoc#13] opened 2015-07-16 21:30 UTC
See example [here](https://rawgit.com/openEHR/specifications-RM/master/docs/support/support.html#_iso8601_time_class)

**Comment by bostjanl** [comment] 2015-08-09 21:19
Is this maybe a duplicate of #8?

**Closed as completed** 2015-11-06 13:15 UTC
Labels: bug
